### ISSUE TITLE
Everything is fine.. but can't work with termux proot-distro and under termux bash make.sh not available

### ISSUE THREAD

**Issue by Saikatsaha1996** [research-note/termux-opencl#6]

**Comment by AITCK** [comment]
~/termux-opencl $ bash build.sh
In file included from vector-add.c:17:
In file included from ../OpenCL-Headers/CL/cl.h:20:
../OpenCL-Headers/CL/cl_version.h:22:9: warning: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0) [-W#pragma-messages]
#pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
        ^
vector-add.c:145:18: warning: 'clCreateCommandQueue' is deprecated [-Wdeprecated-declarations]
        command_queue = clCreateCommandQueue(context, device_id, 0, &ret);
                        ^
../OpenCL-Headers/CL/cl.h:1909:66: note: 'clCreateCommandQueue' has been explicitly marked deprecated here
                     cl_int *                       errcode_ret) CL_API_SUFFIX__VERSION_1_2_DEPRECATED;
                                                                 ^
../OpenCL-Headers/CL/cl_platform.h:108:72: note: expanded from macro 'CL_API_SUFFIX__VERSION_1_2_DEPRECATED'
    #define CL_API_SUFFIX__VERSION_1_2_DEPRECATED CL_API_SUFFIX_COMMON CL_API_SUFFIX_DEPRECATED
                                                                       ^
../OpenCL-Headers/CL/cl_platform.h:78:51: note: expanded from macro 'CL_API_SUFFIX_DEPRECATED'
  #define CL_API_SUFFIX_DEPRECATED __attribute__((deprecated))
                                                  ^
2 warnings generated.
ld.lld: error: unable to find library -lOpenCL
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Saikatsaha1996** [comment]
> ~/termux-opencl $ bash build.sh In file included from vector-add.c:17: In file included from ../OpenCL-Headers/CL/cl.h:20: ../OpenCL-Headers/CL/cl_version.h:22:9: warning: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0) [-W#pragma-messages] #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)") ^ vector-add.c:145:18: warning: 'clCreateCommandQueue' is deprecated [-Wdeprecated-declarations] command_queue = clCreateCommandQueue(context, device_id, 0, &ret); ^ ../OpenCL-Headers/CL/cl.h:1909:66: note: 'clCreateCommandQueue' has been explicitly marked deprecated here cl_int * errcode_ret) CL_API_SUFFIX__VERSION_1_2_DEPRECATED; ^ ../OpenCL-Headers/CL/cl_platform.h:108:72: note: expanded from macro 'CL_API_SUFFIX__VERSION_1_2_DEPRECATED' #define CL_API_SUFFIX__VERSION_1_2_DEPRECATED CL_API_SUFFIX_COMMON CL_API_SUFFIX_DEPRECATED ^ ../OpenCL-Headers/CL/cl_platform.h:78:51: note: expanded from macro 'CL_API_SUFFIX_DEPRECATED' #define CL_API_SUFFIX_DEPRECATED **attribute**((deprecated)) ^ 2 warnings generated. ld.lld: error: unable to find library -lOpenCL clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

>>>pkg install clinfo clvk opencl-headers -y
&& Than check 
>>>clinfo
